name: ec2-creation
on: [push] # triggers
jobs:
  terraform:
    runs-on: ubuntu-latest # Linux OS. We can have windows or MAC
    steps: # stages
      - name: checkout the Code
        uses: actions/checkout@v5

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: run init
        run: terraform init

      - name: run plan
        run: terraform plan