name: ec2-creation
on: [push] # triggers
jobs:
  terraform:
    runs-on: ubuntu-latest # Linux OS. We can have windows or MAC
    steps: # stages
      - name: checkout the Code
        uses: actions/checkout@v5

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: run init
        run: terraform init

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your desired AWS region

      - name: run plan
        run: terraform plan

      - name: run apply
        run: terraform apply -auto-approve